services:
  mage:
    image: mageai/mageai:${MAGE_VERSION}
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAGE_VERSION: ${MAGE_VERSION}
        PROJECT_NAME: ${PROJECT_NAME}
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: ${ENV}
    ports:
      - "6789:6789"
    volumes:
      - .:/home/src
    restart: unless-stopped
